      - name: Run fetcher
        run: |
          python scripts/fetch_affix.py

      - name: List outputs (debug)
        run: |
          echo "--- MANIFEST ---"
          test -f data/affix/manifest.json && cat data/affix/manifest.json || echo "manifest.json não existe"
          echo "--- TREE ---"
          ls -lahR data/affix || true
          echo "--- GIT STATUS ---"
          git status --porcelain
