 name: Index PDFs (Affix/Alter) + Deploy

on:
  push:
    paths:
      - "data/**"
      - "scripts/**"
      - ".github/workflows/indexer.yml"
  schedule:
    - cron: "0 */6 * * *"     # a cada 6h
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Poppler (pdftotext)
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Build index (txt + manifest.json)
        run: npm run build:index

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact (public/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
