name: Index PDFs (Affix/Alter) + Deploy

on:
  push:
    paths:
      - "data/**"
      - "scripts/**"
      - ".github/workflows/indexer.yml"
  schedule:
    - cron: "0 */6 * * *"   # a cada 6h
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Poppler (pdftotext)
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Install deps
        run: npm ci || npm i

      - name: Build index (txt + manifest.json)
        run: npm run build:index

      - name: Commit updated public/**
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public
          git diff --quiet --cached || git commit -m "chore(index): update public index"
          git push

      - name: Upload Pages artifact (public/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

        on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:
  push:
    paths: ["data/**","scripts/**",".github/workflows/indexer.yml"]
